### ISSUE TITLE
Calibrate stereo camera error

### ISSUE THREAD

**Issue by edgar-explorer** [slightech/MYNT-EYE-OKVIS-Sample#3]
cc@cc-desktop:~/kalibr_ws$ kalibr_bagcreater --folder ~/catkin_ws/src/MYNT-EYE-OKVIS-Sample/build/cameraimu/ --output-bag awsome.bag

Traceback (most recent call last):
  File "/home/cc/kalibr_ws/devel/bin/kalibr_bagcreater", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/cc/kalibr_ws/src/kalibr-master/aslam_offline_calibration/kalibr/python/kalibr_bagcreater", line 121, in <module>
    imumsg, timestamp = createImuMessge(row[0], row[1:4], row[4:7])
  File "/home/cc/kalibr_ws/src/kalibr-master/aslam_offline_calibration/kalibr/python/kalibr_bagcreater", line 95, in createImuMessge
    rosimu.linear_acceleration.y = float(alpha[1])
IndexError: list index out of range
cc@cc-desktop:~/kalibr_ws$ kalibr_bagcreater --folder ~/catkin_ws/src/MYNT-EYE-OKVIS-Sample/build/cameraimu/ --output-bag awsome.bag
importing libraries
Traceback (most recent call last):
  File "/home/cc/kalibr_ws/devel/bin/kalibr_bagcreater", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/cc/kalibr_ws/src/kalibr-master/aslam_offline_calibration/kalibr/python/kalibr_bagcreater", line 121, in <module>
    imumsg, timestamp = createImuMessge(row[0], row[1:4], row[4:7])
  File "/home/cc/kalibr_ws/src/kalibr-master/aslam_offline_calibration/kalibr/python/kalibr_bagcreater", line 95, in createImuMessge
    rosimu.linear_acceleration.y = float(alpha[1])
IndexError: list index out of range
cc@cc-desktop:~/kalibr_ws$ kalibr_bagcreater --folder ~/catkin_ws/src/MYNT-EYE-OKVIS-Sample/build/cameraimu/ --output-bag awsome.bag
importing libraries
Traceback (most recent call last):
  File "/home/cc/kalibr_ws/devel/bin/kalibr_bagcreater", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/cc/kalibr_ws/src/kalibr-master/aslam_offline_calibration/kalibr/python/kalibr_bagcreater", line 121, in <module>
    imumsg, timestamp = createImuMessge(row[0], row[1:4], row[4:7])
  File "/home/cc/kalibr_ws/src/kalibr-master/aslam_offline_calibration/kalibr/python/kalibr_bagcreater", line 95, in createImuMessge
    rosimu.linear_acceleration.y = float(alpha[1])
IndexError: list index out of range

**Comment by bergercookie** [comment]
@cumtchenchang try inspecting the imu.csv file. There may be corrupted/incomplete lines towards the end of the file
